export const FETCHING_TEMPERATURE = 'FETCHING_TEMPERATURE';
export const FETCHING_TEMPERATURE_SUCCESS = 'FETCHING_TEMPERATURE_SUCCESS';
export const FETCHING_TEMPERATURE_FAILED = 'FETCHING_TEMPERATURE_FAILED';

export const CREATE_SOCKET = 'CREATE_SOCKET';
export const CREATE_SOCKET_SUCCESS = 'CREATE_SOCKET_SUCCESS';
export const CREATE_SOCKET_FAILED = 'CREATE_SOCKET_FAILED';
export const DESTROY_SOCKET = 'DESTROY_SOCKET';

export const SET_USERNAME = 'SET_USERNAME';
export const ADD_USER = 'ADD_USER';
export const DEL_USER = 'DEL_USER';
export const ALLNAMES_TO_SERVER='ALLNAMES_TO_SERVER';

